runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  DB_NAME: ''*******''
  INSTANCE_CONNECTION_NAME: 'automationwbrise:us-east5:scorecard'
  DB_USER: ''*******''
  DB_PASSWORD: '*******'
  DB_PASS: ''*******''
  DB_HOST: ''*******''
  DB_PORT: ''*******''
  DATABASE_URL: 'postgresql://'*******''

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
